module Constants
  def self.csv_column_names_lookup
    {
      "pkSeqID" => "pkSeqID",
      "PkSeqID" => "pkSeqID",
      "pk_Seq_ID" => "pkSeqID",
      "stime" => "stime",
      "Stime" => "stime",
      "flgs" => "flgs",
      "Flgs" => "flgs",
      "flag" => "flgs",
      "flgs_number" => "flgs_number",
      "proto" => "proto",
      "Proto" => "proto",
      "Protocol"=> "proto",
      "protocol"=> "proto",
      "protocol_type" => "proto",
      "proto_number" => "proto_number",
      "saddr" => "saddr",
      "Source IP" => "saddr",
      "source IP" => "saddr",
      "srcip"=> "saddr",
      "sport" => "sport",
      "Source Port"=> "sport",
      "source Port"=> "sport",
      "daddr" => "daddr",
      "Destination IP"=> "daddr",
      "destination IP"=> "daddr",
      "dstip" => "daddr",
      "dport" => "dport",
      "Destination Port"=> "dport",
      "destination Port"=> "dport",
      "dsport"=> "dport",
      "pkts" => "pkts",
      "Pkts" => "pkts",
      "bytes" => "bytes",
      "state" => "state",
      "State" => "state",
      "state_number" => "state_number",
      "ltime" => "ltime",
      "seq" => "seq",
      "dur" => "dur",
      "mean" => "mean",
      "stddev" => "stddev",
      "sum" => "sum",
      "min" => "min",
      "max" => "max",
      "spkts" => "spkts",
      "dpkts" => "dpkts",
      "sbytes" => "sbytes",
      "src_bytes" => "sbytes",
      "dbytes" => "dbytes",
      "dst_bytes" => "dbytes",
      "rate" => "rate",
      "serror_rate" => "rate",
      "srate" => "srate",
      "drate" => "drate",
      "TnBPSrcIP" => "TnBPSrcIP",
      "TnBPDstIP" => "TnBPDstIP",
      "TnP_PSrcIP" => "TnP_PSrcIP",
      "TnP_PDstIP" => "TnP_PDstIP",
      "TnP_PerProto" => "TnP_PerProto",
      "TnP_Per_Dport" => "TnP_Per_Dport",
      "AR_P_Proto_P_SrcIP" => "AR_P_Proto_P_SrcIP",
      "AR_P_Proto_P_DstIP" => "AR_P_Proto_P_DstIP",
      "N_IN_Conn_P_DstIP" => "N_IN_Conn_P_DstIP",
      "N_IN_Conn_P_SrcIP" => "N_IN_Conn_P_SrcIP",
      "AR_P_Proto_P_Sport" => "AR_P_Proto_P_Sport",
      "AR_P_Proto_P_Dport" => "AR_P_Proto_P_Dport",
      "Pkts_P_State_P_Protocol_P_DestIP" => "Pkts_P_State_P_Protocol_P_DestIP",
      "Pkts_P_State_P_Protocol_P_SrcIP" => "Pkts_P_State_P_Protocol_P_SrcIP",
    }
  end

  def self.required_csv_headers
    [
      "pkSeqID",
      "stime",
      "saddr",
      "sport",
      "daddr",
      "dport",
      "pkts",
      "bytes",
      "ltime",
      "dur",
      "sum",
      "spkts",
      "dpkts",
      "sbytes",
      "dbytes",
      "srate",
      "TnBPSrcIP",
      "TnBPDstIP",
      "TnP_PSrcIP",
      "TnP_PDstIP",
      "TnP_PerProto",
      "TnP_Per_Dport",
      "Pkts_P_State_P_Protocol_P_DestIP",
      "Pkts_P_State_P_Protocol_P_SrcIP",
    ]
  end
end
