module Constants
  def self.csv_column_names_lookup
    {
      "pkSeqID" => "pkSeqID",
      "pk_Seq_ID" => "pkSeqID",
      "stime" => "stime",
      "flgs" => "flgs",
      "flgs_number" => "flgs_number",
      "proto" => "proto",
      "proto_number" => "proto_number",
      "saddr" => "saddr",
      "sport" => "sport",
      "daddr" => "daddr",
      "dport" => "dport",
      "pkts" => "pkts",
      "bytes" => "bytes",
      "state" => "state",
      "state_number" => "state_number",
      "ltime" => "ltime",
      "seq" => "seq",
      "dur" => "dur",
      "mean" => "mean",
      "stddev" => "stddev",
      "sum" => "sum",
      "min" => "min",
      "max" => "max",
      "spkts" => "spkts",
      "dpkts" => "dpkts",
      "sbytes" => "sbytes",
      "dbytes" => "dbytes",
      "rate" => "rate",
      "srate" => "srate",
      "drate" => "drate",
      "TnBPSrcIP" => "TnBPSrcIP",
      "TnBPDstIP" => "TnBPDstIP",
      "TnP_PSrcIP" => "TnP_PSrcIP",
      "TnP_PDstIP" => "TnP_PDstIP",
      "TnP_PerProto" => "TnP_PerProto",
      "TnP_Per_Dport" => "TnP_Per_Dport",
      "AR_P_Proto_P_SrcIP" => "AR_P_Proto_P_SrcIP",
      "AR_P_Proto_P_DstIP" => "AR_P_Proto_P_DstIP",
      "N_IN_Conn_P_DstIP" => "N_IN_Conn_P_DstIP",
      "N_IN_Conn_P_SrcIP" => "N_IN_Conn_P_SrcIP",
      "AR_P_Proto_P_Sport" => "AR_P_Proto_P_Sport",
      "AR_P_Proto_P_Dport" => "AR_P_Proto_P_Dport",
      "Pkts_P_State_P_Protocol_P_DestIP" => "Pkts_P_State_P_Protocol_P_DestIP",
      "Pkts_P_State_P_Protocol_P_SrcIP" => "Pkts_P_State_P_Protocol_P_SrcIP",
    }
  end
end
